# basic options
title: COM1003 프로그래밍2
author: 도경구
email: doh@hanyang.ac.kr
description: 한양대학교 ERICA 소프트웨어융합대학 신산업소프트웨어전공 2021년 1학기
twitter_username:
github_username: Doggzone

# Build settings
markdown: kramdown
theme: minima